// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/dns/check/[subdomain].ts";
import * as $1 from "./routes/api/dns/register.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/register.tsx";
import * as $4 from "./routes/success.tsx";
import * as $$0 from "./islands/CountUp.tsx";
import * as $$1 from "./islands/SubDomainInput.tsx";

const manifest = {
  routes: {
    "./routes/api/dns/check/[subdomain].ts": $0,
    "./routes/api/dns/register.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/register.tsx": $3,
    "./routes/success.tsx": $4,
  },
  islands: {
    "./islands/CountUp.tsx": $$0,
    "./islands/SubDomainInput.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
